apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yml
  - 05-config.yml
  - 10-postgres.yml
  - 20-minio.yml
  - 30-minio-init.yml
  - 40-api.yml
  - 41-job-launcher-rbac.yml
  - 42-job-launcher.yml
  - 50-mvsep-job-template.yml
