apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - secrets.yml

images:
  - name: drumtrackai/backend
    newName: ghcr.io/<YOUR_GITHUB_ORG_OR_USER>/drumtrackai-backend
    newTag: latest
  - name: drumtrackai/job-launcher
    newName: ghcr.io/<YOUR_GITHUB_ORG_OR_USER>/drumtrackai-job-launcher
    newTag: latest
  - name: drumtrackai/mvsep-worker
    newName: ghcr.io/<YOUR_GITHUB_ORG_OR_USER>/drumtrackai-mvsep-worker
    newTag: latest

patchesStrategicMerge:
  - patch-mvsep-gpu.yml
  - patch-resources.yml
