"""Upsert Jamstix-derived drummer personas into the admin DB.

Usage (from project root):

    python admin/tools/upsert_jamstix_personas.py

This will:
- Read jamstix_persona_seed.json generated by
  llm_training_project/jamstix_tools/jamstix_job_generator.py
- For each seed, create/update a row in drummer_personas with:
  - persona_id  : e.g. "jamstix.Rock.Phil"
  - display_name: Jamstix player display name (e.g. "Phil")
  - archetypes_json: currently an empty list (Jamstix uses styles, not MVSEP archetypes)
  - style_json : JSON containing Jamstix metadata and a placeholder for
                 aggregated style metrics to be filled later from MIDI analysis.

Jamstix metadata is stored under keys like:

    {
      "source": "jamstix",
      "jamstix_player_id": "Rock/Phil",
      "jamstix_category": "Rock",
      "jamstix_style_ids": ["Rock/16th Rock 01", ...]
    }

Later, a separate tool can merge in numeric groove metrics derived from the
Jamstix-generated MIDI and/or real tracks for that drummer.
"""

import json
import os
import sqlite3
from pathlib import Path
from typing import List, Dict, Any

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_DB = PROJECT_ROOT / "admin" / "drumtrackai.db"

# Location of the Jamstix persona seed file produced by jamstix_job_generator.py
JAMSTIX_TOOLS_DIR = PROJECT_ROOT / "llm_training_project" / "jamstix_tools"
PERSONA_SEED_PATH = JAMSTIX_TOOLS_DIR / "jamstix_persona_seed.json"


def get_db_path() -> Path:
    env = os.getenv("DRUMTRACKAI_DB_PATH")
    return Path(env) if env else DEFAULT_DB


def ensure_drummer_personas_schema(conn: sqlite3.Connection) -> None:
    cur = conn.cursor()
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS drummer_personas (
            persona_id TEXT PRIMARY KEY,
            display_name TEXT NOT NULL,
            archetypes_json TEXT NOT NULL,
            style_json TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        """
    )
    conn.commit()


def upsert_persona(
    conn: sqlite3.Connection,
    persona_id: str,
    display_name: str,
    archetypes: List[str],
    style: Dict[str, Any],
) -> None:
    cur = conn.cursor()
    cur.execute(
        """
        INSERT INTO drummer_personas (
            persona_id, display_name, archetypes_json, style_json
        ) VALUES (?, ?, ?, ?)
        ON CONFLICT(persona_id) DO UPDATE SET
            display_name=excluded.display_name,
            archetypes_json=excluded.archetypes_json,
            style_json=excluded.style_json,
            updated_at=CURRENT_TIMESTAMP
        """,
        (
            persona_id,
            display_name,
            json.dumps(archetypes),
            json.dumps(style),
        ),
    )
    conn.commit()


def load_persona_seeds() -> List[Dict[str, Any]]:
    if not PERSONA_SEED_PATH.exists():
        raise SystemExit(
            f"Jamstix persona seed file not found: {PERSONA_SEED_PATH}. "
            "Run llm_training_project/jamstix_tools/jamstix_job_generator.py first."
        )
    data = json.loads(PERSONA_SEED_PATH.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise SystemExit(f"Unexpected seed JSON shape in {PERSONA_SEED_PATH}: expected a list.")
    return data


def main() -> None:
    db_path = get_db_path()
    print(f"Using DB: {db_path}")
    print(f"Loading Jamstix persona seeds from: {PERSONA_SEED_PATH}")

    seeds = load_persona_seeds()
    print(f"Found {len(seeds)} Jamstix persona seeds.")

    conn = sqlite3.connect(db_path)
    try:
        ensure_drummer_personas_schema(conn)

        upserted = 0
        for seed in seeds:
            persona_id = seed.get("persona_id")
            display_name = seed.get("display_name")
            jamstix_player_id = seed.get("jamstix_player_id")
            jamstix_category = seed.get("jamstix_category")
            jamstix_style_ids = seed.get("style_ids") or []

            if not persona_id or not display_name or not jamstix_player_id:
                print(f"Skipping invalid seed (missing id/name/player): {seed}")
                continue

            # For Jamstix personas we don't have MVSEP archetypes; keep this empty
            archetypes: List[str] = []

            # Initial style blob: Jamstix metadata + placeholder for later metrics
            style: Dict[str, Any] = {
                "source": "jamstix",
                "jamstix_player_id": jamstix_player_id,
                "jamstix_category": jamstix_category,
                "jamstix_style_ids": jamstix_style_ids,
                # Placeholder for numeric style metrics derived from MIDI
                "metrics": {},
            }

            upsert_persona(conn, persona_id, display_name, archetypes, style)
            upserted += 1

    finally:
        conn.close()

    print(f"Upserted {upserted} Jamstix personas into drummer_personas.")


if __name__ == "__main__":
    main()
